### ISSUE TITLE
Rename some leftovers

### ISSUE THREAD

**Issue by Phr33d0m** [StuartIanNaylor/zram-swap-config#1]
https://github.com/StuartIanNaylor/zram-swap-config/blob/a37a3b8a1382935042e7f1e6b04694ec34055978/zram-swap-config#L59

**Comment by StuartIanNaylor** [comment]
Many thanks will do.
I actually feel there is a huge need for Ubuntu to fix zram-config-0.5.deb as it gets emulated and copied so much.
I started with a simple need to use a zram drive for log2ram hence the above, initially had all zram config even swaps moved to L2R then realised L2R should just be Log2Ram.
I will have a look through as there maybe others and see if I can prune.
If you have any idea on tidying or improving the script please do it main purpose was to demonstrate the working methods of https://www.kernel.org/doc/Documentation/blockdev/zram.txt and how the above has little correlation, even its name  zram-config-0.5.deb that you are unable to configure in any way is so broken on so many levels I don't think I have ever seen its like.
Its absolutely amazing how many times its been emulated and copied without any check to the original kernel documents.

zram-swap-config IMHO should be like any other Linux config where it will run on install with no need for conf edit, but if needed complete granular control can be made.

I do feel the following lines are the remit of zram-swap-config because the move to zram means a move from what are HDD tuned parameters.
	# Enable page-cluster tweak 0 pages=1
	sysctl vm.page-cluster=${PAGE_CLUSTER}
	sysctl vm.swappiness=${SWAPPINESS}

The defaults are very much tuned to HDD parameters and the above 2 are no-brainers, but there is a whole rake of default parameters that are extremely 'standard pc' orientated.

Not really sure about the Swappiness-load-balancer but just wanted to demonstrate the problem with static best compromise system parameters especially with secondary effects such as load which zram has.
In what can be said to be 'normal' load zram giving more memory availability through higher swappiness, can run at much higher levels than normal, even 100.
The problem is that its unlikely due to boot and initial load and that swappiness is a static set-point reduced because of the intense short term load of boot and initialisation of services and applications.
Its a shame as with constant spare ticks so there is no increase in process queue sysctl vm.swappiness=100 long term can give quite a performance boost, with zram.
Probably dropping swappiness on load will force pages out at an inopportune moment even if decompress is far lighter in operation.

Zram really does have a lot to offer in the IoT / Maker scene but any implementation and config must at least check no other device exists.

`  if [ ! -d "/sys/class/zram-control" ]; then`

Zram is a hot_add and remove system but dev/zram0 is flawed as I think it can only be removed via a rmod and there may be higher devices existing.

Overall Zram-swap-config should be highly configurable but also run from a default install and include zram specific tuning parameters.

And really Ubuntu should fix their completely broken package! It gets used, copied and emulated a hell of a lot on a misguided assumption its Ubuntu and correct.
