### ISSUE TITLE
Zram0 Dynamic

### ISSUE THREAD

**Issue by Fungraphic** [StuartIanNaylor/zram-swap-config#2]
hello.
 I made a USB key in full install (as for an install on HDD)
 I configure a zram to optimize when I boot on an old pc that only has for example 1G of ram.

 I would like some help to make a script that changes the size of the zram0 dynamically according to the size of the memory present on the PC.

 Example if the PC to 2G ram hard then the script is 2G * 2 and gives the value of 4G zram0 and all this at startup without intervention from me.

thank's

**Comment by StuartIanNaylor** [comment]
Already does its the mem_factor which is a % of totalmem=$(free|awk '/^Mem:/{print $2}')
On install /etc/zram-swap-config.conf = MEM_FACTOR=50 which is 50%
Just `sudo nano /etc/zram-swap-config.conf` and set to MEM_FACTOR=100 which is 100%
The disk_size DRIVE_FACTOR=210 is by default a pessimistic minimum compression ratio of 210% or 1:2.1
With a MEM_FACTOR=50 its 50% of ram * DRIVE_FACTOR=210 210% so 105%.
You can set MEM_FACTOR=100 but you will never be able to use that amount due to buffer/cache allocation.
If you do a `free -h'`
```
pi@raspberrypi:~/zram-config $ free -h
              total        used        free      shared  buff/cache   available
Mem:           927M         37M        806M        6.2M         83M        835M
Swap:          849M          0B        849M
```
You will see how much is free as the MEM_FACTOR= is based on the total 927M in the above.
You prob go to approx MEM_FACTOR=90-95 max but when you do manage to use MEM_FACTOR=100 you would likely get OOM errors but think it will just never happen as the cache_pressure will just steal the ram it needs.
So you will always lose some of the total to shared / buff/cache (6.2M         83M) in the above.

If overall available memory is critical then you prob could be less pessimistic with the DRIVE_FACTOR=210 and with LZO/4 got to DRIVE_FACTOR=300 3* MEM_FACTOR.
If you are prepared to use a slower Alg such as deflate then maybe even DRIVE_FACTOR=450

`sudo nano /etc/zram-swap-config.conf`
```
MEM_FACTOR=90
DRIVE_FACTOR=450
COMP_ALG=deflate
SWAP_DEVICES=1
SWAP_PRI=75
PAGE_CLUSTER=0
SWAPPINESS=100
```
That is prob the max you can go.
```
pi@raspberrypi:~/zram-config $ zramctl
NAME       ALGORITHM DISKSIZE  DATA COMPR TOTAL STREAMS MOUNTPOINT
/dev/zram1 lz4           750M    4K   76B    4K       4 [SWAP]
```
DATA is uncompressed size and TOTAL is how much ZRAM is using as it has a 0.1% overhead plus the blocks & inodes of the swap.
When you use deflate due to zramctl only having text strings for LZO/LZ4 the ALG will be blank but it will still work.
Deflate will be slower than LZO/4 but keep an eye out on the ratio of TOTAL:DATA for swaps because of speed I use LZ4 but with deflate you may even be able to get 1:4 or higher.

**Comment by Fungraphic** [comment]
ok thank's for your reactivity and your explanation.
